Merged:

*   CA_ZCTA
*   TOTAL POPULATION Census 2010_clean
*   COMORBIDITY_FINAL
*   Education_Clean
*   Employment_Final
*   DEATH_FINAL
*   Median_Income_Clean
*   Population_by_sex_age_final
*   OSM_Healthcare_poi_by_ZCTA
*   Heatlh_listing_FINAL
*   zip_county
*   race_final

In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive

In [2]:
import pandas as pd

In [3]:
base_path = "Shareddrives/GCP hackathon/Data/Final Data"

In [4]:
df = pd.read_csv(f"{base_path}/CA_ZCTA.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ZCTA    1762 non-null   int64
dtypes: int64(1)
memory usage: 13.9 KB

In [5]:
df

       ZCTA
0     90001
1     90002
2     90003
3     90004
4     90005
...     ...
1757  96148
1758  96150
1759  96155
1760  96161
1761  95314

[1762 rows x 1 columns]

In [6]:
total_population_df = pd.read_csv(f"{base_path}/TOTAL POPULATION Census 2010_clean.csv")

total_population_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33120 entries, 0 to 33119
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ZCTA              33120 non-null  int64
 1   Total Population  33120 non-null  int64
dtypes: int64(2)
memory usage: 517.6 KB

In [7]:
total_population_df

        ZCTA  Total Population
0        601             18570
1        602             41520
2        603             54689
3        606              6615
4        610             29016
...      ...               ...
33115  99923                87
33116  99925               819
33117  99926              1460
33118  99927                94
33119  99929              2338

[33120 rows x 2 columns]

In [8]:
df = df.merge(total_population_df, how='left', on='ZCTA')
df

       ZCTA  Total Population
0     90001             57110
1     90002             51223
2     90003             66266
3     90004             62180
4     90005             37681
...     ...               ...
1757  96148               788
1758  96150             29792
1759  96155                 8
1760  96161             18451
1761  95314                 0

[1762 rows x 2 columns]

In [9]:
comorbidity_df = pd.read_csv(f"{base_path}/COMORBIDITY_FINAL.csv")

comorbidity_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32409 entries, 0 to 32408
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           32409 non-null  int64
 1   ZCTA5                32409 non-null  int64
 2   insurance_access     32409 non-null  float64
 3   ARTHRITIS_CrudePrev  32409 non-null  float64
 4   DRINKING             32409 non-null  float64
 5   BPHIGH_CrudePrev     32409 non-null  float64
 6   CANCER_CrudePrev     32409 non-null  float64
 7   CASTHMA_CrudePrev    32409 non-null  float64
 8   CHD_CrudePrev        32409 non-null  float64
 9   COPD_CrudePrev       32409 non-null  float64
 10  HIGHCHOL_CrudePrev   32409 non-null  float64
 11  CSMOKING_CrudePrev   32409 non-null  float64
 12  DIABETES_CrudePrev   32409 non-null  float64
 13  OBESITY_CrudePrev    32409 non-null  float64
 14  STROKE_CrudePrev     32409 non-null  float64
dtypes: float64(13), int64(2)
memory usage: 3.7 MB

In [10]:
comorbidity_df.drop(columns=['Unnamed: 0'], inplace=True)

comorbidity_df

       ZCTA5  insurance_access  ...  OBESITY_CrudePrev  STROKE_CrudePrev
0       8240              13.2  ...               34.9               3.6
1       8904              13.2  ...               34.9               3.6
2       8065              13.2  ...               34.9               3.6
3      28443              12.4  ...               31.1               3.2
4       3103              17.7  ...               35.7               3.0
...      ...               ...  ...                ...               ...
32404  90265               6.4  ...               22.7               2.6
32405  92567              19.8  ...               34.3               3.2
32406  98237              12.3  ...               32.2               4.0
32407  87564              12.2  ...               25.3               3.4
32408  95628               7.9  ...               25.7               3.1

[32409 rows x 14 columns]

In [11]:
df = df.merge(comorbidity_df, how='left', left_on='ZCTA', right_on='ZCTA5')
df.drop(columns=['ZCTA5'], inplace=True)

df

       ZCTA  Total Population  ...  OBESITY_CrudePrev  STROKE_CrudePrev
0     90001             57110  ...               35.2               3.3
1     90002             51223  ...               36.0               3.8
2     90003             66266  ...               36.5               3.7
3     90004             62180  ...               25.5               2.5
4     90005             37681  ...               25.4               2.8
...     ...               ...  ...                ...               ...
1757  96148               788  ...               26.2               2.5
1758  96150             29792  ...               27.3               2.7
1759  96155                 8  ...                NaN               NaN
1760  96161             18451  ...               24.2               2.1
1761  95314                 0  ...                NaN               NaN

[1762 rows x 15 columns]

In [12]:
education_df = pd.read_csv(f"{base_path}/Education_Clean.csv")

education_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 8 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   id                                  1762 non-null   object
 1   Geographic Area Name                1762 non-null   object
 2   Total_Population_18plus             1762 non-null   int64
 3   Less than high school graduate      1762 non-null   int64
 4   High school graduate                1762 non-null   int64
 5   Some college or associate's degree  1762 non-null   int64
 6   Bachelor's degree or higher         1762 non-null   int64
 7   zcta                                1762 non-null   int64
dtypes: int64(6), object(2)
memory usage: 110.2+ KB

In [13]:
education_df.drop(columns=['id', 'Geographic Area Name'], inplace=True)
education_df.rename(columns={'zcta':'ZCTA'}, inplace=True)

education_df

      Total_Population_18plus  ...   ZCTA
0                       40854  ...  90001
1                       36045  ...  90002
2                       50055  ...  90003
3                       48931  ...  90004
4                       32524  ...  90005
...                       ...  ...    ...
1757                      963  ...  96146
1758                      471  ...  96148
1759                    24289  ...  96150
1760                        0  ...  96155
1761                    14190  ...  96161

[1762 rows x 6 columns]

In [14]:
df = df.merge(education_df, how='left', on='ZCTA')

df

       ZCTA  ...  Bachelor's degree or higher
0     90001  ...                         2097
1     90002  ...                         1917
2     90003  ...                         2718
3     90004  ...                        16177
4     90005  ...                         9643
...     ...  ...                          ...
1757  96148  ...                          142
1758  96150  ...                         6529
1759  96155  ...                            0
1760  96161  ...                         7037
1761  95314  ...                            0

[1762 rows x 20 columns]

In [15]:
employment_df = pd.read_csv(f"{base_path}/Employment_Final.csv")

employment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1762 non-null   object
 1   Geographic Area Name  1762 non-null   object
 2   Employed_16_above     1762 non-null   int64
 3   zcta                  1762 non-null   int64
dtypes: int64(2), object(2)
memory usage: 55.2+ KB

In [16]:
employment_df.drop(columns=['id', 'Geographic Area Name'], inplace=True)
employment_df.rename(columns={'zcta':'ZCTA'}, inplace=True)

employment_df

      Employed_16_above   ZCTA
0                 42853  90001
1                 38146  90002
2                 52804  90003
3                 50096  90004
4                 33217  90005
...                 ...    ...
1757                973  96146
1758                471  96148
1759              24911  96150
1760                  0  96155
1761              14763  96161

[1762 rows x 2 columns]

In [17]:
df = df.merge(employment_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  Bachelor's degree or higher  Employed_16_above
0     90001             57110  ...                         2097              42853
1     90002             51223  ...                         1917              38146
2     90003             66266  ...                         2718              52804
3     90004             62180  ...                        16177              50096
4     90005             37681  ...                         9643              33217
...     ...               ...  ...                          ...                ...
1757  96148               788  ...                          142                471
1758  96150             29792  ...                         6529              24911
1759  96155                 8  ...                            0                  0
1760  96161             18451  ...                         7037              14763
1761  95314                 0  ...                            0                 95

[1762 rows x 21 columns]

In [18]:
death_df = pd.read_csv(f"{base_path}/DEATH_FINAL.csv")

death_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1572 entries, 0 to 1571
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1572 non-null   int64
 1   ZCTA         1572 non-null   int64
 2   All_death    1438 non-null   float64
 3   Heart_death  1319 non-null   float64
dtypes: float64(2), int64(2)
memory usage: 49.2 KB

In [19]:
death_df.drop(columns=['Unnamed: 0'], inplace=True)

death_df

       ZCTA  All_death  Heart_death
0     95314        0.0          0.0
1     90001      275.0         57.0
2     90002      252.0         62.0
3     90003      375.0         91.0
4     90004      285.0         63.0
...     ...        ...          ...
1567  96132        NaN          0.0
1568  96133        NaN          0.0
1569  96135        NaN          0.0
1570  96141        NaN          0.0
1571  96142        NaN          0.0

[1572 rows x 3 columns]

In [20]:
df = df.merge(death_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  All_death  Heart_death
0     90001             57110  ...      275.0         57.0
1     90002             51223  ...      252.0         62.0
2     90003             66266  ...      375.0         91.0
3     90004             62180  ...      285.0         63.0
4     90005             37681  ...      193.0         39.0
...     ...               ...  ...        ...          ...
1757  96148               788  ...        NaN          NaN
1758  96150             29792  ...      167.0         31.0
1759  96155                 8  ...        NaN          NaN
1760  96161             18451  ...       67.0         16.0
1761  95314                 0  ...        0.0          0.0

[1762 rows x 23 columns]

In [21]:
income_df = pd.read_csv(f"{base_path}/Median_Income_Clean.csv")

income_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    1762 non-null   object
 1   Geographic Area Name  1762 non-null   object
 2   Income                1762 non-null   float64
 3   zcta                  1762 non-null   int64
dtypes: float64(1), int64(1), object(2)
memory usage: 55.2+ KB

In [22]:
income_df.drop(columns=['id', 'Geographic Area Name'], inplace=True)
income_df.rename(columns={'zcta':'ZCTA'}, inplace=True)

income_df

        Income   ZCTA
0     43360.00  90001
1     37285.00  90002
2     40598.00  90003
3     49675.00  90004
4     38491.00  90005
...        ...    ...
1757  76851.00  96146
1758  73611.00  96148
1759  57396.00  96150
1760  76437.11  96155
1761  98924.00  96161

[1762 rows x 2 columns]

In [23]:
df = df.merge(income_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  Heart_death    Income
0     90001             57110  ...         57.0  43360.00
1     90002             51223  ...         62.0  37285.00
2     90003             66266  ...         91.0  40598.00
3     90004             62180  ...         63.0  49675.00
4     90005             37681  ...         39.0  38491.00
...     ...               ...  ...          ...       ...
1757  96148               788  ...          NaN  73611.00
1758  96150             29792  ...         31.0  57396.00
1759  96155                 8  ...          NaN  76437.11
1760  96161             18451  ...         16.0  98924.00
1761  95314                 0  ...          0.0  76437.11

[1762 rows x 24 columns]

In [24]:
demographics_df = pd.read_csv(f"{base_path}/Population_by_sex_age.csv")

demographics_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ZCTA                  1762 non-null   int64
 1   Total                 1762 non-null   int64
 2   Total Male%           1762 non-null   float64
 3   Total Female%         1762 non-null   float64
 4   Male: Under 5%        1762 non-null   float64
 5   Male: 5 to 17%        1762 non-null   float64
 6   Male: 18 to 39%       1762 non-null   float64
 7   Male: 40 to 59%       1762 non-null   float64
 8   Male: 60 and Over%    1762 non-null   float64
 9   Female: Under 5%      1762 non-null   float64
 10  Female: 5 to 17%      1762 non-null   float64
 11  Female: 18 to 39%     1762 non-null   float64
 12  Female: 40 to 59%     1762 non-null   float64
 13  Female: 60 and Over%  1762 non-null   float64
dtypes: float64(12), int64(2)
memory usage: 192.8 KB

In [25]:
demographics_df.drop(columns=['Total'], inplace=True)

demographics_df

       ZCTA  Total Male%  ...  Female: 40 to 59%  Female: 60 and Over%
0     90001     0.507647  ...           0.128509              0.059575
1     90002     0.516613  ...           0.110810              0.058798
2     90003     0.476943  ...           0.119733              0.058928
3     90004     0.490099  ...           0.122664              0.054510
4     90005     0.492790  ...           0.132307              0.090715
...     ...          ...  ...                ...                   ...
1757  96146     0.508151  ...           0.140661              0.161155
1758  96148     0.558079  ...           0.144978              0.088210
1759  96150     0.608621  ...           0.063793              0.096552
1760  96155     0.531012  ...           0.124390              0.115559
1761  96161     0.000000  ...           0.000000              0.000000

[1762 rows x 13 columns]

In [26]:
df = df.merge(demographics_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  Female: 40 to 59%  Female: 60 and Over%
0     90001             57110  ...           0.128509              0.059575
1     90002             51223  ...           0.110810              0.058798
2     90003             66266  ...           0.119733              0.058928
3     90004             62180  ...           0.122664              0.054510
4     90005             37681  ...           0.132307              0.090715
...     ...               ...  ...                ...                   ...
1757  96148               788  ...           0.144978              0.088210
1758  96150             29792  ...           0.063793              0.096552
1759  96155                 8  ...           0.124390              0.115559
1760  96161             18451  ...           0.000000              0.000000
1761  95314                 0  ...           0.167816              0.078927

[1762 rows x 36 columns]

In [27]:
osm_df = pd.read_csv(f"{base_path}/OSM_Healthcare_poi_by_ZCTA.csv")

osm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799 entries, 0 to 798
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ZCTA                799 non-null    int64
 1   OSM_healthcare_poi  799 non-null    int64
dtypes: int64(2)
memory usage: 12.6 KB

In [28]:
osm_df

      ZCTA  OSM_healthcare_poi
0    90001                  12
1    90002                   2
2    90003                   8
3    90004                   3
4    90005                   1
..     ...                 ...
794  96107                   1
795  96130                   3
796  96135                   1
797  96150                   1
798  96161                   2

[799 rows x 2 columns]

In [29]:
df = df.merge(osm_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  Female: 60 and Over%  OSM_healthcare_poi
0     90001             57110  ...              0.059575                12.0
1     90002             51223  ...              0.058798                 2.0
2     90003             66266  ...              0.058928                 8.0
3     90004             62180  ...              0.054510                 3.0
4     90005             37681  ...              0.090715                 1.0
...     ...               ...  ...                   ...                 ...
1757  96148               788  ...              0.088210                 NaN
1758  96150             29792  ...              0.096552                 1.0
1759  96155                 8  ...              0.115559                 NaN
1760  96161             18451  ...              0.000000                 2.0
1761  95314                 0  ...              0.078927                 NaN

[1762 rows x 37 columns]

In [30]:
health_facilities_df = pd.read_csv(f"{base_path}/Heatlh_listing_FINAL.csv")

health_facilities_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        1169 non-null   int64
 1   ZCTA                              1169 non-null   int64
 2   zip_level_facilities              1169 non-null   int64
 3   zip_level_facilities_filtered     1169 non-null   float64
 4   county_level_facilities           1169 non-null   int64
 5   county_level_facilities_filtered  1169 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 54.9 KB

In [31]:
health_facilities_df.drop(columns=['Unnamed: 0'], inplace=True)

health_facilities_df

       ZCTA  ...  county_level_facilities_filtered
0     89449  ...                              27.0
1     90001  ...                            1247.0
2     90002  ...                            1247.0
3     90003  ...                            1247.0
4     90004  ...                            1247.0
...     ...  ...                               ...
1164  96137  ...                               8.0
1165  96143  ...                              21.0
1166  96150  ...                              27.0
1167  96161  ...                              21.0
1168  97415  ...                               0.0

[1169 rows x 5 columns]

In [32]:
df = df.merge(health_facilities_df, how='left', on='ZCTA')

df

       ZCTA  ...  county_level_facilities_filtered
0     90001  ...                            1247.0
1     90002  ...                            1247.0
2     90003  ...                            1247.0
3     90004  ...                            1247.0
4     90005  ...                            1247.0
...     ...  ...                               ...
1757  96148  ...                               NaN
1758  96150  ...                              27.0
1759  96155  ...                               NaN
1760  96161  ...                              21.0
1761  95314  ...                               NaN

[1762 rows x 41 columns]

In [33]:
county_df = pd.read_csv(f"{base_path}/zip_county.csv")

county_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1760 entries, 0 to 1759
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1760 non-null   int64
 1   ZCTA         1760 non-null   int64
 2   zip          1760 non-null   int64
 3   county_name  1760 non-null   object
dtypes: int64(3), object(1)
memory usage: 55.1+ KB

In [34]:
county_df.drop(columns=['Unnamed: 0', 'zip'], inplace=True)

county_df

       ZCTA  county_name
0     90001  Los Angeles
1     90002  Los Angeles
2     90003  Los Angeles
3     90004  Los Angeles
4     90005  Los Angeles
...     ...          ...
1755  96146       Placer
1756  96148       Placer
1757  96150    El Dorado
1758  96155    El Dorado
1759  96161       Nevada

[1760 rows x 2 columns]

In [35]:
df = df.merge(county_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  county_level_facilities_filtered  county_name
0     90001             57110  ...                            1247.0  Los Angeles
1     90002             51223  ...                            1247.0  Los Angeles
2     90003             66266  ...                            1247.0  Los Angeles
3     90004             62180  ...                            1247.0  Los Angeles
4     90005             37681  ...                            1247.0  Los Angeles
...     ...               ...  ...                               ...          ...
1757  96148               788  ...                               NaN       Placer
1758  96150             29792  ...                              27.0    El Dorado
1759  96155                 8  ...                               NaN    El Dorado
1760  96161             18451  ...                              21.0       Nevada
1761  95314                 0  ...                               NaN          NaN

[1762 rows x 42 columns]

In [36]:
race_df = pd.read_csv(f"{base_path}/race_final.csv")

race_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1762 entries, 0 to 1761
Data columns (total 10 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   ZCTA                                              1762 non-null   int64
 1   Total                                             1762 non-null   int64
 2   Population of one race                            1762 non-null   float64
 3   White alone                                       1762 non-null   float64
 4   Black or African American alone                   1762 non-null   float64
 5   American Indian and Alaska Native alone           1762 non-null   float64
 6   Asian alone                                       1762 non-null   float64
 7   Native Hawaiian and Other Pacific Islander alone  1762 non-null   float64
 8   Some Other Race alone                             1762 non-null   float64
 9   Two or More Races                                 1762 non-null   float64
dtypes: float64(8), int64(2)
memory usage: 137.8 KB

In [37]:
race_df.drop(columns=['Total'], inplace=True)

race_df

       ZCTA  Population of one race  ...  Some Other Race alone  Two or More Races
0     90001                0.962791  ...               0.486097           0.037209
1     90002                0.962146  ...               0.414638           0.037854
2     90003                0.962032  ...               0.406966           0.037968
3     90004                0.955323  ...               0.269444           0.044677
4     90005                0.955309  ...               0.263793           0.044691
...     ...                     ...  ...                    ...                ...
1757  96146                0.979502  ...               0.006589           0.020498
1758  96148                0.977157  ...               0.083756           0.022843
1759  96150                0.965830  ...               0.113554           0.034170
1760  96155                0.875000  ...               0.000000           0.125000
1761  96161                0.978755  ...               0.083356           0.021245

[1762 rows x 9 columns]

In [38]:
df = df.merge(race_df, how='left', on='ZCTA')

df

       ZCTA  Total Population  ...  Some Other Race alone  Two or More Races
0     90001             57110  ...               0.486097           0.037209
1     90002             51223  ...               0.414638           0.037854
2     90003             66266  ...               0.406966           0.037968
3     90004             62180  ...               0.269444           0.044677
4     90005             37681  ...               0.263793           0.044691
...     ...               ...  ...                    ...                ...
1757  96148               788  ...               0.083756           0.022843
1758  96150             29792  ...               0.113554           0.034170
1759  96155                 8  ...               0.000000           0.125000
1760  96161             18451  ...               0.083356           0.021245
1761  95314                 0  ...               0.000000           0.000000

[1762 rows x 50 columns]

In [39]:
df.to_csv(f'{base_path}/Merged_data.csv', index=False)

# Cleaning starts here

In [40]:
to_normalize = ["Less than high school graduate", "High school graduate", "Some college or associate's degree", "Bachelor's degree or higher", "Employed_16_above"]
for i in to_normalize:
  df[i] = df[i]/df['Total Population']

In [41]:
# Comobordities by 100 to match [0,1] percentage scale used
for col_name in comorbidity_df.columns:
  if col_name == "ZCTA5":
    continue
  df[col_name] = df[col_name]/100

In [42]:
# Dropping rows with less than 1000 people
df = df[df['Total Population']>=1000]

In [43]:
df.isna().sum()

ZCTA                                                  0
Total Population                                      0
insurance_access                                      0
ARTHRITIS_CrudePrev                                   0
DRINKING                                              0
BPHIGH_CrudePrev                                      0
CANCER_CrudePrev                                      0
CASTHMA_CrudePrev                                     0
CHD_CrudePrev                                         0
COPD_CrudePrev                                        0
HIGHCHOL_CrudePrev                                    0
CSMOKING_CrudePrev                                    0
DIABETES_CrudePrev                                    0
OBESITY_CrudePrev                                     0
STROKE_CrudePrev                                      0
Total_Population_18plus                               0
Less than high school graduate                        0
High school graduate                                  0
Some college or associate's degree                    0
Bachelor's degree or higher                           0
Employed_16_above                                     0
All_death                                            49
Heart_death                                         270
Income                                                0
Total Male%                                           0
Total Female%                                         0
Male: Under 5%                                        0
Male: 5 to 17%                                        0
Male: 18 to 39%                                       0
Male: 40 to 59%                                       0
Male: 60 and Over%                                    0
Female: Under 5%                                      0
Female: 5 to 17%                                      0
Female: 18 to 39%                                     0
Female: 40 to 59%                                     0
Female: 60 and Over%                                  0
OSM_healthcare_poi                                  650
zip_level_facilities                                266
zip_level_facilities_filtered                       266
county_level_facilities                             266
county_level_facilities_filtered                    266
county_name                                           0
Population of one race                                0
White alone                                           0
Black or African American alone                       0
American Indian and Alaska Native alone               0
Asian alone                                           0
Native Hawaiian and Other Pacific Islander alone      0
Some Other Race alone                                 0
Two or More Races                                     0
dtype: int64

In [44]:
# Replacing empty healthcare facilities with 0
# df[['OSM_healthcare_poi','zip_level_facilities', 'county_level_facilities']] = df[['OSM_healthcare_poi','zip_level_facilities', 'county_level_facilities']].fillna(0)

In [45]:
# Dropping ZCTA with no county name/data
df = df[~df.county_name.isna()]

In [46]:
# Replacing empty deaths with 0 (Population is very low at ZCTA so probably no deaths)
# df[['All_death','Heart_death']] = df[['All_death','Heart_death']].fillna(0)

In [47]:
# comorbidity_df.columns

In [48]:
# Replacing empty comobordities with state median
# for col_name in comorbidity_df.columns:
#   if col_name == "ZCTA5":
#     continue
#   df[col_name] = df[col_name].fillna(value=df[col_name].median())

In [49]:
df.to_csv(f'{base_path}/Clean_data.csv', index=False)