In [1]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

Mounted at /gdrive
/gdrive

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
base_path = "Shareddrives/GCP hackathon/Data/"

In [4]:
df = pd.read_csv(f"{base_path}/Final Data/Clean_data.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1413 entries, 0 to 1412
Data columns (total 50 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   ZCTA                                              1413 non-null   int64
 1   Total Population                                  1413 non-null   int64
 2   insurance_access                                  1413 non-null   float64
 3   ARTHRITIS_CrudePrev                               1413 non-null   float64
 4   DRINKING                                          1413 non-null   float64
 5   BPHIGH_CrudePrev                                  1413 non-null   float64
 6   CANCER_CrudePrev                                  1413 non-null   float64
 7   CASTHMA_CrudePrev                                 1413 non-null   float64
 8   CHD_CrudePrev                                     1413 non-null   float64
 9   COPD_CrudePrev                                    1413 non-null   float64
 10  HIGHCHOL_CrudePrev                                1413 non-null   float64
 11  CSMOKING_CrudePrev                                1413 non-null   float64
 12  DIABETES_CrudePrev                                1413 non-null   float64
 13  OBESITY_CrudePrev                                 1413 non-null   float64
 14  STROKE_CrudePrev                                  1413 non-null   float64
 15  Total_Population_18plus                           1413 non-null   int64
 16  Less than high school graduate                    1413 non-null   float64
 17  High school graduate                              1413 non-null   float64
 18  Some college or associate's degree                1413 non-null   float64
 19  Bachelor's degree or higher                       1413 non-null   float64
 20  Employed_16_above                                 1413 non-null   float64
 21  All_death                                         1364 non-null   float64
 22  Heart_death                                       1143 non-null   float64
 23  Income                                            1413 non-null   float64
 24  Total Male%                                       1413 non-null   float64
 25  Total Female%                                     1413 non-null   float64
 26  Male: Under 5%                                    1413 non-null   float64
 27  Male: 5 to 17%                                    1413 non-null   float64
 28  Male: 18 to 39%                                   1413 non-null   float64
 29  Male: 40 to 59%                                   1413 non-null   float64
 30  Male: 60 and Over%                                1413 non-null   float64
 31  Female: Under 5%                                  1413 non-null   float64
 32  Female: 5 to 17%                                  1413 non-null   float64
 33  Female: 18 to 39%                                 1413 non-null   float64
 34  Female: 40 to 59%                                 1413 non-null   float64
 35  Female: 60 and Over%                              1413 non-null   float64
 36  OSM_healthcare_poi                                763 non-null    float64
 37  zip_level_facilities                              1147 non-null   float64
 38  zip_level_facilities_filtered                     1147 non-null   float64
 39  county_level_facilities                           1147 non-null   float64
 40  county_level_facilities_filtered                  1147 non-null   float64
 41  county_name                                       1413 non-null   object
 42  Population of one race                            1413 non-null   float64
 43  White alone                                       1413 non-null   float64
 44  Black or African American alone                   1413 non-null   float64
 45  American Indian and Alaska Native alone           1413 non-null   float64
 46  Asian alone                                       1413 non-null   float64
 47  Native Hawaiian and Other Pacific Islander alone  1413 non-null   float64
 48  Some Other Race alone                             1413 non-null   float64
 49  Two or More Races                                 1413 non-null   float64
dtypes: float64(46), int64(3), object(1)
memory usage: 552.1+ KB